id: P84242D2A
initial_creation_type: input
source_metadata:
  title: Rongtön Sheja Künrig Series
  language: bo
  description: Rongtön Sheja Kunrig (rong ston shes bya kun rig), also known as Shakya
    Gyaltsen, (shakya rgyal mtshan, 1367-1449) was one of the greatest scholars of
    the Sakya school, renowned especially for his mastery of the prajñāpāramitā teachings.
    He founded Nalendra Monastery in 1436.
  volume:
    57465a3427934a298de6f1ef9826e7a0:
      title: 'The Joyous Entrance to the Path to Liberation: How to Practise the Six
        Transcendent Perfections'
      parent: Advice
    d9005bfd16b04ecf8ff03f834b061b3e:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    580e9c7196b64b38822b8e5aab39e81c:
      title: 'Clarifying the Essence: A Summary of the Instructions on the View of
        the Middle Way'
      parent: Middle Way
    d22813f91aec47ae88faf873f5c5c6a5:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Praise
    327996b5bd0a4b36ad6d86efc4284112:
      title: 'The Sun that Causes the Lotus of Intelligence to Bloom: In Praise of
        the Lineage of Gurus for the Noble Abhidharma'
      parent: Praise
    3a83158354d542158635958d0682eadc:
      title: Elucidating the Essence of the Instructions for Entering the Three Gateways
        to Liberation
      parent: Three Gateways to Liberation
    5b1aa0831b594adeadaf17481b5decc5:
      title: 'The Excellent Path of the Great Vehicle: How to Meditate on the Three
        Gateways to Liberation According to the Mahāyāna'
      parent: Three Gateways to Liberation
created_at: '2022-03-01T01:24:12.900215'
last_modified_at: '2022-03-01T01:24:12.900217'
statistics:
  total_words: 3039
  total_non_words: 219
quality:
  non_words_ratio: 0.07
